control_homepage:
    path:     /
    defaults: { _controller: ControlBundle:Default:index }

control_client_index:
    path:     /control/client/index
    defaults: { _controller: ControlBundle:Client:index }


control_client_add:
    path:     /control/client/add
    defaults: { _controller: ControlBundle:Client:add }

control_client_create:
    path:     /control/client/create
    defaults: { _controller: ControlBundle:Client:create }
    methods: POST
    
control_client_edit:
    path:   /control/client/edit/{id}
    defaults: { _controller: ControlBundle:Client:edit }
    
control_client_update:
    path:   /control/client/update/{id}
    defaults: { _controller: ControlBundle:Client:update }
    methods: POST


    
